version: 2

jobs:
  rubocop:
    working_directory: ~/carters
    docker:
      - image: circleci/ruby:2.5.1-node
    steps:
      - checkout

      - restore_cache:
          keys:
            - carters-bundle-v3-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle install
          command: bundle check || bundle install --path vendor/bundle

      - save_cache:
          key: carters-bundle-v3-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          name: Restore Yan Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Rubocop
          command: bundle exec rubocop

  prettier:
    working_directory: ~/carters
    docker:
      - image: circleci/ruby:2.5.1-node
    steps:
      - checkout

      - restore_cache:
          keys:
            - carters-bundle-v3-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle install
          command: bundle check || bundle install --path vendor/bundle

      - save_cache:
          key: carters-bundle-v3-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          name: Restore Yan Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Prettier
          command: yarn prettier

  rspec:
    working_directory: ~/carters
    docker:
      - image: circleci/ruby:2.5.1-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          RAILS_ENV: test
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: carters_test
    steps:
      - checkout

      - restore_cache:
          keys:
            - carters-bundle-v3-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle install
          command: bundle check || bundle install --path vendor/bundle

      - save_cache:
          key: carters-bundle-v3-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          name: Restore Yan Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:migrate

      - run:
          name: Run rspec
          command: bundle exec rspec --format documentation

  deployment:
    working_directory: ~/carters
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  pipeline:
    jobs:
      - prettier
      - rubocop
      - rspec:
          requires:
            - rubocop
            - prettier
      - deployment:
          requires:
            - rspec
          filters:
            branches:
              only: master
